version: "3"

services:
  rabbit:
    image: rabbitmq:3.6-management-alpine
    container_name: rabbitmq
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
    networks:
      - qa-service
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 10

  embedder:
    image: pacificus/tf_use_embedder_qa
    container_name: embedder
    restart: always
    depends_on:
      - rabbit
    ports:
      - "5002:5000"
    networks:
      - qa-service
    volumes:
      - ./models/1:/models/use
    healthcheck:
      test: curl -s http://embedder:5000/readiness || exit 1
      interval: 30s
      timeout: 10s
      retries: 10

  elastic:
    image: elasticsearch:8.4.3
    container_name: es_index
    restart: always
    ports:
      - "9300:9300"
      - "9200:9200"
    env_file:
      - ./es.env
    networks:
      - qa-service
    healthcheck:
      test: curl -s http://es:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 10

  search:
    image: pacificus/search_qa
    container_name: search
    restart: always
    depends_on:
      - rabbit
      - elastic
      - embedder
    ports:
      - "5003:5003"
    networks:
      - qa-service

  streamlit_app:
    image: pacificus/streamlit_app
    container_name: streamlit_app
    restart: always
    depends_on:
      - rabbit
      - elastic
      - embedder
    ports:
      - "8501:8501"
    networks:
      - qa-service


networks:
  qa-service:
