import random

words = [
    "Accuracy Score",
    "Activation Function",
    "Algorithm",
    "Apache Spark",
    "API",
    "Artificial Intelligence (AI)",
    "Artificial Neural Networks (ANN)",
    "Backpropagation (BP)",
    "Bayesian Network",
    "Bayes Theorem",
    "Bias",
    "Bias - Variance Tradeoff",
    "Big Data",
    "Binomial Distribution",
    "Business Analyst",
    "Business Analytics(BA)",
    "Business Intelligence(BI)",
    "Categorical Variable",
    "Categorical Variable Classification",
    "Clustering",
    "Computer Science",
    "Computer Vision",
    "Confusion Matrix",
    "Continuous Variable",
    "Correlation",
    "Cost Function",
    "Covariance",
    "Cross - Validation(not validated)",
    "Dashboard",
    "Data Analysis(DA)",
    "Data Analyst",
    "Database",
    "Database Management System (DBMS)",
    "Data Consumer",
    "Data Engineer",
    "Data Engineering (DE)",
    "Data Enrichment",
    "Dataframe",
    "Data Governance",
    "Data Journalism",
    "Data Lake",
    "Data Literacy",
    "Data Mining",
    "Data Modeling",
    "Data Pipeline",
    "Data Science (DS)",
    "Data Scientist",
    "Dataset",
    "Data Structure",
    "Data Visualization",
    "Data Warehouse",
    "Data Wrangling",
    "Decision Tree",
    "Deep Learning (DL)",
    "Dimensionality Reduction",
    "EDA",
    "ELT",
    "ETL",
    "Evaluation Metrics",
    "False Negative (FN)",
    " Type II Error)",
    "False Positive (FP)",
    "Type I Error)",
    "Feature",
    "Feature Engineering",
    "Feature Selection",
    "F - Score",
    "Gradient Descent",
    "Hadoop",
    "Hyperparameter",
    "Hypothesis",
    "Imputation",
    "K - Means",
    "K - Nearest Neighbors(KNN)",
    "Linear Algebra",
    "Linear Regression",
    "Logistic Regression",
    "Machine Learning (ML)",
    "Mean",
    "Mean Absolute Error(MAE)",
    "Mean Squared Error(MSE)",
    "Median",
    "Mode",
    "Model Tuning",
    "Multivariate Modeling",
    "Naive Bayes",
    "Natural Language Processing (NLP)",
    "Normalization",
    "NoSQL",
    "Null Hypothesis",
    "OpenSource",
    "Ordinal Variable",
    "Outlier",
    "Overfitting",
    "Parameter",
    "Precision",
    "Predictive Analytics",
    "Principal Component Analysis (PCA)",
    "Python",
    "Random Forest",
    "Recall",
    "Regression",
    "Reinforcement Learning (RL)",
    "Root Mean Squared Error (RMSE)",
    "Sampling Error",
    "SQL",
    "Standard Deviation",
    "Supervised Learning",
    "SVM",
    "Synthetic Data",
    "Target Variable",
    "TestSet",
    "Time Series",
    "Training Set",
    "True Negative (TN)",
    "True Positive (TP)",
    "Underfitting",
    "UnivariateModeling",
    "UnstructuredData",
    "UnsupervisedLearning",
    "Variance",
    "WebScraping",
    "Z - Score",
]


def generate_query():
    idx = random.randint(0, len(words) - 1)
    return f"What is {words[idx]}?"


def get_n_docs():
    return random.randint(5, 21)
