data:
  so_dataset_url: https://archive.org/download/stackexchange/datascience.meta.stackexchange.com.7z #https://archive.org/download/stackexchange/datascience.stackexchange.com.7z
  so_dataset_path: data/raw
  processed_path: data/processed
  posts_filename: Posts.xml
  embeddings_filename: embeddings.pkl
model:
  model_path: models/use