indexing:
  elastic:
    index_name: stackoverflow_tensorflow_use
search_app:
  url: http://search:5003/find
streamlit:
  title: StackOverflow QA service
  local_css_path: css/style.css
  remote_css_path: https://fonts.googleapis.com/icon?family=Material+Icons
  icon: search
  slider:
    min_value: 5
    max_value: 20
    value: 5
    step: 1
